Created Entities Feedback and NumDiTelefono
C01-GlucoseGuardian/WebBackend pull request #4
Opened 2023-01-18 16:00 UTC by domenicocifelli

Created Entities

2023-01-18 16:13 UTC, veetaw commented
Credo che il costruttore non debba avere id

2023-01-18 16:20 UTC, veetaw commented
lgtm

2023-01-18 19:59 UTC, Scient122 requested changes
Checklist non verificata

2023-01-18 21:29 UTC, HandyMenny approved these changes
@Scient122 risolti i problemi di checkstyle

2023-01-19 09:48 UTC, merged

2023-01-19 09:49 UTC, veetaw reviewed
lgtm